export const VOXEL_SIZE = 2
export const VOXEL_HEIGHT = 0.5
export const CHUNK_SIZE = 32
export const CHUNK_HEIGHT = 64
export const WORLD_WIDTH_CHUNKS = 23
export const WORLD_DEPTH_CHUNKS = 23
export const WORLD_WIDTH_VOXELS = WORLD_WIDTH_CHUNKS * CHUNK_SIZE // 736
export const WORLD_DEPTH_VOXELS = WORLD_DEPTH_CHUNKS * CHUNK_SIZE // 736
